const student = [

    {
        id          : 1,
        roll        : 1,
        name        : `Ananda`,
        age         : 12,
        location    : `Panthapath`,
        gender      : `Male`,
        bn          : 90,
        en          : 50,
        math        : 57,
        s           : 65,
        ss          : 69,
        rel         : 80,
    },
    {
        id          : 2,
        roll        : 2,
        name        : `Jillur`,
        age         : 29,
        location    : `Mirpur`,
        gender      : `Male`,
        bn          : 95,
        en          : 51,
        math        : 57,
        s           : 60,
        ss          : 69,
        rel         : 85,
    },
    {
        id          : 3,
        roll        : 3,
        name        : `Suma`,
        age         : 18,
        location    : `Khulna`,
        gender      : `Female`,
        bn          : 53,
        en          : 50,
        math        : 40,
        s           : 65,
        ss          : 62,
        rel         : 70,
    },
    {
        id          : 4,
        roll        : 4,
        name        : `Juyal`,
        age         : 23,
        location    : `Uttara`,
        gender      : `Male`,
        bn          : 20,
        en          : 50,
        math        : 45,
        s           : 65,
        ss          : 65,
        rel         : 85,
    },
    {
        id          : 5,
        roll        : 5,
        name        : `Ananto`,
        age         : 20,
        location    : `Banani`,
        gender      : `Male`,
        bn          : 53,
        en          : 80,
        math        : 57,
        s           : 62,
        ss          : 43,
        rel         : 78,
    },

];